import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.sqldelight)
}

kotlin {
    androidTarget()
    
    jvm {
        mainRun {
            mainClass.set("com.mrm.minierp.MainKt")
        }
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }
    
    sourceSets {
        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.activity.compose)
            implementation(libs.ktor.client.okhttp)
            implementation(libs.sqldelight.android.driver)
        }
        commonMain.dependencies {
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.ktor.client.core)
            implementation(libs.navigation.compose)
            implementation(libs.sqldelight.runtime)
            implementation(libs.sqldelight.coroutines)
            implementation(libs.multiplatform.settings)
            implementation(libs.multiplatform.settings.coroutines)
            implementation(libs.kotlinx.datetime)
            @Suppress("DEPRECATION")
            implementation(compose.materialIconsExtended)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
        jvmMain.dependencies {
            implementation(compose.desktop.currentOs)
            implementation(libs.kotlinx.coroutinesSwing)
            implementation(libs.ktor.client.cio)
            implementation(libs.sqldelight.sqlite.driver)
            implementation("com.github.librepdf:openpdf:2.0.3")
        }
    }
}

sqldelight {
    databases {
        create("MiniErpDatabase") {
            packageName.set("com.mrm.minierp.database")
        }
    }
}

android {
    namespace = "com.mrm.minierp"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.mrm.minierp"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = libs.versions.app.versionCode.get().toInt()
        versionName = libs.versions.app.version.get()
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies {
    debugImplementation(libs.compose.uiTooling)
}

compose.desktop {
    application {
        mainClass = "com.mrm.minierp.MainKt"

        nativeDistributions {
            modules("java.sql")
            targetFormats(TargetFormat.Msi, TargetFormat.Exe)
            packageName = "MiniErp"
            packageVersion = libs.versions.app.version.get()
        }
    }
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
    kotlinOptions {
        jvmTarget = "11"
    }
}

val generateBuildInfo by tasks.creating {
    val version = libs.versions.app.version.get()
    val outputDir = file("src/commonMain/kotlin/com/mrm/minierp/generated")
    val outputFile = file("${outputDir.absolutePath}/BuildInfo.kt")
    
    inputs.property("version", version)
    outputs.file(outputFile)
    
    doLast {
        if (!outputDir.exists()) outputDir.mkdirs()
        outputFile.writeText("""
            package com.mrm.minierp.generated

            /**
             * GENERATED FILE. DO NOT MODIFY MANUALLY.
             * This file is generated by the generateBuildInfo Gradle task.
             */
            object BuildInfo {
                const val APP_VERSION = "$version"
            }
        """.trimIndent())
    }
}

// Asegurar que la tarea se ejecute antes de la compilación
tasks.matching { it.name.contains("compileKotlin") }.configureEach {
    dependsOn(generateBuildInfo)
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}
