name: Build Windows Executable

on:
  push:
    branches: [ "main", "master" ]
    tags:
      - 'v*' # Se activa cuando creas un tag que empiece por v (ej: v1.0.0)
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew :composeApp:packageExe

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiniErp-Windows-Exe
          path: composeApp/build/compose/binaries/main/exe/*.exe

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: composeApp/build/compose/binaries/main/exe/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
